/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as maxjaMinterSol from "./MaxjaMinter.sol";
export type { maxjaMinterSol };
export type { MaxjaAirdrop } from "./MaxjaAirdrop";
