/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as maxjaMinterSol from "./MaxjaMinter.sol";
export { MaxjaAirdrop__factory } from "./MaxjaAirdrop__factory";
