/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MaxjaAirdrop__factory } from "./MaxjaAirdrop__factory";
export { MaxjaMinter__factory } from "./MaxjaMinter__factory";
